### ISSUE TITLE
It didn't build and work in 2 minutes, help me please

### ISSUE THREAD

**Issue by Kyraze** [Decathlon/ara#117] opened 2019-05-29 12:52 UTC
Hello, 
I'm using Postman for API testing and I'd like to see how to use ara to report and keep an history.

In your "How to build and make it work in 2 minutes" : 
I have two issues : 
First is the command to "create a MySQL Dockerized database locally", Docker has firewall problem, I'm trying to find out how to make it work, didn't see "Security" dept yet.
Second is the 4th step : I have the following error : 

![image](https://user-images.githubusercontent.com/44932677/58558271-a75d8880-8220-11e9-9270-503f6d31f7b5.png)

I'm using redhat open jdk (1.8) and Docker first timer, so please be patient,
Thank you for your help.

**Comment by dktsni** [comment] 2019-06-07 09:04
Hi @Kyraze 

Thanks for your interest on ARA ! 

Your second problem seems to be directly related to your Docker problem. The fact is that the database `ara-dev` is not found by the application, so the docker container could clearly be the root cause.

Could you send us the result of the command after running the installation again please : 
```
docker container ps
```

(this command will shows the active Docker containers).

Also could you send us the full log of the `./manage-db.sh create` please ?

**Comment by Kyraze** [comment] 2019-06-07 09:26
Hello @dktsni 

I solved the docker problem yesterday actually and I was able to launch ARA : you're right it was docker and it was about ports used by docker and a "File sharing and Printer" service using the same ports, so I had to deactivate it.
Now I'm trying to export postman reports to ARA, I didn't see where in the doc provided how to do that, could you please assist me on that? 
Here is where I am so far : 
I put an "desensitized" test report : https://github.com/Kyraze/Shooter/blob/master/collection_poc.json
I configured in ARA : Manage project -> Source as a source : "https://github.com/Kyraze/Shooter/blob/{{branch}}/ "
And now I don't know how to extract/upload data from the sources

**Comment by dktsni** [comment] 2019-06-07 09:46
Glad to read that your installation problem is fixed :D 

Could you please open an another issue to explain your upload problem ? (Just if someone else has the problem they could easily find it when doing a search)

I'll close this issue since your initial problem is fixed.

**Closed by dktsni** 2019-06-07 09:46 UTC

**Comment by Kyraze** [comment] 2019-06-07 09:49
![HOWTODOCKER](https://user-images.githubusercontent.com/44932677/59096039-41f15200-891a-11e9-986d-818812e27fd4.PNG)

In case someone get the same issue, but they're most likely better at Docker than me
